site_view/site_blueprint.py
from flask import Flask,Blueprint,request,render_template,redirect,make_response,jsonify,url_for,session,g
from site_control.user_mgmt import User
from flask_login import login_user,current_user,logout_user
from site_control.ariticles_mgmt import Article
import datetime
from site_control.site_sessionmgmt import BlogSession
from flask import flash
import bcrypt
import jwt

#sqlalchemy에서 Members 클래스 가져온다

#register에서 DB에 저장하려면 db객체가 필요한데 다른 데서 끌고올 방법을 모르겠네요...



#login_user:서버단에서 세션 쿠키셋관련 임포트
#current_user: 세션확인 할 때 사용
#main코드에 app에 최초 before request함수를 정의해둬서 블루프린트로 정의된 라우팅으로 들어와도 자동으로 before requset가 실행됨.
senior_school=Blueprint('senior_school',__name__)



########################################## 홈페이지 로그인 확인 후 렌더링 #############################
@senior_school.route('/home')
def home():
    '''
    #로그인 세션정보가 없을 경우
    if not session.get('user_id'):
        return render_template('home.html')
    #로그인 세션정보('userid')가 있을 경우
    else:
        user_id=session.get('user_id')
        return render_template('home.html', user_id=user_id)
    '''
    #세션확인 후 구독이력 확인
    if current_user.is_authenticated:
        rows = Article.get_home_board()
        return render_template('home.html',rows=rows)
        #return render_template("home.html",user_id=current_user.user_id)#여기에 jinja2에 들어갈 변수를 같이 넣어준다.
    else:
        rows = Article.get_home_board()
        return render_template('home.html', rows=rows)
   
# <---  로그인 확인 후 로그인 하지않았다면 로그인 페이지, 벌써 로그인 중이라면 홈 요청 및 로그인 아이디도 같이 넘겨줌  --->


#########it 기술##########
@senior_school.route('/tech_description/')
def tech():
    return render_template("it_tech.html")

@senior_school.route('/wifi_tech/')
def wifi():
    return render_template("wifi_desc.html")

@senior_school.route('/bluetooth_tech/')
def bluetooth_tech():
    return render_template("bluetooth_desc.html")
    #######################################  mypage 관련 라우팅 #####################################


@senior_school.route('/mypage/')
def mypage():
    if current_user.is_authenticated:
        return render_template("mypage.html")
    else:
        return render_template("login_register.html")

#######################################  게시판 관련 라우팅 #####################################

@senior_school.route('/bullet/')
def bullet():
    #page = request.args.get('page', type=int, default=1) 
    rows=Article.get_board()
    #rows=rows.paginate(page, per_page=10)
    
    return render_template("bulletBoard.html", rows=rows)

@senior_school.route('/article_page/<title>/<context>')
def article_page(title,context):
    return render_template("article.html",title=title, row=context)


@senior_school.route('/write_article')
def write_article():
    return render_template('write_article.html')


@senior_school.route('/delete_article/<title>')
def delete_article_article(title):
    if current_user.is_authenticated :
        if Article.check_owe(current_user.user_id,title=title)==1:
            row = Article.delete(current_user.user_id,title)
            return redirect('/bullet')
        else:
            return render_template('home.html'),401
    else:
        return redirect('/login_register')

@senior_school.route('/posting',methods=['POST'])
def posting():
    if current_user.is_authenticated:
        wuser_id=current_user.user_id
        title=request.form['title']
        context=request.form['context']
        Article.write_post(wuser_id,title,context)
        return redirect('/bullet')
    else:
        #flash("로그인 해주세요")
        return redirect('/login_register')



###################################### 가입 및 로그인 라우팅 #######################################
@senior_school.route('/set_register', methods=['POST'])
def set_register():
    en_password=bcrypt.hashpw(request.form['password'].encode('UTF-8'),bcrypt.gensalt()) #암호화
    #VARCHAR 에 맞게 decode해서 문자열로 변환
    #en_password = en_password.decode('UTF-8')
    user=User.create(request.form['user_id'],en_password,request.form['user_name'])
    print(en_password)
    if(user == None):
        return "같은 아이디가 존재합니다", 400
    
    #session['user_id'] = user.user_id    #user_id를 세션에 저장한다.
    #return render_template('home.html', user_id=request.form['user_id'])
    login_user(user,remember=True, duration=datetime.timedelta(days=30))
    return redirect('/home') 

@senior_school.route('/set_login', methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return "wrong route",401
    else:
        user_id=request.form['user_id']
        password=request.form['password']

    try:
        # ID/PW 조회Query 실행
        user = User.find(user_id)

        if user.user_id == user_id and bcrypt.checkpw(password.encode('utf-8'),user.password):    #쿼리 데이터가 존재하면
            login_user(user,remember=True, duration=datetime.timedelta(days=30))
            #session['user_id'] = user_id    #user_id를 세션에 저장한다.
            return redirect("/home")
        else:
            return '비밀번호가 맞지 않습니다', 400 #아이디는 맞는데 비번 틀릴때
    except:
        return "존재하지 않는 아이디입니다", 400  #테이블에 user_id 자체가 없을때   

  
@senior_school.route('/login_register')
def login_register():
    return render_template("login_register.html")


############################################################################

################################# 로그아웃 ####################################
@senior_school.route('/logout')
def logout():
    logout_user() #어차피 라우팅 리퀘스트시 세션에 로그인 정보가 있다.
    return render_template("home.html")
    #return redirect('/home')
##########################################################################


@senior_school.route('/macdonalds')
def macdonalds():
    return render_template('macdonalds.html')




@senior_school.route('/fullstack')
def fullstack():    
    if current_user.is_authenticated:#세션확인 후 구독이력 확인
        web_page=BlogSession.get_blog_page(current_user.blog_id)#구독시 페이지정보  
        BlogSession.save_session_info(session['client_id'],current_user.user_email,web_page)
        #로그인한 방문자의 IP등을 세션라이브러리로부터 받아와서 넣는다.      
        return render_template(web_page,user_email=current_user.user_email)#여기에 jinja2에 들어갈 변수를 같이 넣어준다.
    else:
        web_page=BlogSession.get_blog_page()
        BlogSession.save_session_info(session['client_id'],'anonymous',web_page)
        #로그인하지않은 방문자의 IP등을 세션라이브러리로부터 받아와서 넣는다.
        return render_template(web_page)

'''
@senior_school.route('/logout')
def logout():
    User.delete(user_id=current_user.id)
    logout_user() #어차피 라우팅 리퀘스트시 세션에 로그인 정보가 있다.
    return redirect(url_for('blog_bp.fullstack'))


@senior_school.route('/set_login',methods=['GET','POST'])
def set_email():
    if request.method=='GET':
        #print('http check',request.headers)
        print("set_email()",request.args.get('user_email'))
        #return make_response(jsonify(success=True),200) 
        #->vue와 같은 js를 사용하지 않고 서버단에서 풀스택을 구현하는 거라 전체페이지를 리로딩하는 식으로한다.
        #return redirect(url_for('blog_bp.engA'))
        return redirect(url_for(request.form['blog_id']))
    else:
        #print('http check',request.headers)
        #http request의 헤더부분을 가져올 수 있다. 이후 content type를 확인하고 데이터를 어떻게 가져와야하는지 고민하자.
        #content type이 application/json인 경우에는 request.get_json()
        #->print('set_email',request.get_json())
        #print('blog_id',request.form['blog_id'])
        #print('only user_email',request.form['user_email'])
        #post방식으로 데이터를 가져올 수 있다. vue에서 했었음
        ID=request.form['user_id']
        PW=request.form['password']
        login_user(user,remember=True, duration=datetime.timedelta(days=30))
        #로그인 기록유지 시킴 remember me,flask_login google검색
        #세션정보가 플라스크에서 만들어져 셋쿠키로 웹브라우저에 전송, 웹브라우저는 서버주소와 쿠키를 저장,관리를 하면서 다음에 해당서버에 request를 할 때 사용한다. 
        #return redirect(url_for(request.form['blog_id']))
        return redirect('/blueprint/fullstack')
'''

@senior_school.route('/board_main',methods=['GET','POST'])
def board_main():
    print('site control에서 article_mgmt안에 게시판 관련된 클래스 선언 후(mysql과 연결) 관련 내용을 받아와서 일단 프린트 하도록 만들기.')
    #site control에서 article_mgmt안에 게시판 관련된 클래스 선언 후(mysql과 연결) 관련 내용을 받아와서 일단 프린트 하도록 만들기.

templates/article.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.82.0">
    <title>Document</title>

</head>
<body>
    <div class="position-relative overflow-hidden p-3 p-md-0 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
        
          <h1 class="display-4 fw-normal">스터디 룸</h1>
          <p class="lead fw-normal">원하는 방에 들어가서 함께 학습해보세요.</p>
          <!--
          <a class="btn btn-outline-secondary" href="#">Coming soon</a>
          -->
        </div>
        <!--
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
        -->
      </div>
      <hr>
    <div>
    <h3>링크</h3>
    <a href="{{ 'https://jitsi.o-r.kr/' + title }}"> 이동하기</a>
    </div>
    

    <h3>제목</h3>
    {{title}}<br>
    <hr>
    <h3>내용</h3>
    <div>{{row}} <br> </div>
    <hr>
      
      <form action="/delete_article" method="GET">
       <input type="text" name="{{ title }}" style="display: none;" />
        
        <a href="/delete_article/{{title}}"><h5>삭제하기</h5></a>

    </form>

    <button onclick="window.location.href='/bullet'">뒤로가기</button>
    <button onclick="window.location.href='/home'">홈으로</button>

</body>
</html>

templates/bulletBoard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.82.0">
  <title>시니어를 위한 IT 교육 </title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">



  <!-- Bootstrap core CSS -->
  <link href="../static/dist/css/bootstrap.min.css" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="../static/dist/css/carousel.css" rel="stylesheet">
</head>

<body>

  <div class="position-relative overflow-hidden p-3 p-md-0 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
    
      <h1 class="display-4 fw-normal">스터디 룸</h1>
      <p class="lead fw-normal">원하는 방에 들어가서 함께 학습해보세요.</p>
      <!--
      <a class="btn btn-outline-secondary" href="#">Coming soon</a>
      -->
    </div>
    <!--
    <div class="product-device shadow-sm d-none d-md-block"></div>
    <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    -->
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">번호</th>
        <th scope="col">바로 입장하기</th>
        <th scope="col">제목</th>
        <th scope="col">이름</th>
        <th scope="col">날짜</th>
        <!--<th scope="col">   </th>-->
      </tr>
    </thead>
    <tbody>
      {% if rows!= none %}
      {% for row in rows %}
      <tr>
        <td>{{loop.index}}</td>
        <td><a href="{{ 'https://jitsi.o-r.kr/' + row[2] }}"> {{row[2]}}</a></td>
        <td><a href="{{ url_for('senior_school.article_page',title= row[2], context = row[3]) }}"> {{row[2]}}</a></td>
        <td>{{row[1]}}</td>
        <td>{{row[4]}}</td>
        <!--<td>{{row[4]}}</td>-->
      </tr>
      {% endfor %}
      {% else %}
      <h3>데이터가 존재하지 않습니다.</h3>
      {% endif %}
    </tbody>
  </table>
  <a href="{{ url_for('senior_school.write_article') }}" class="btn btn-primary">질문 등록하기</a>
  <br><br>  
  <a href="/home" class="btn btn-primary">홈으로</a>

</body>

</html>

templates/home.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.82.0">
  <title>P-Edu</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">



  <!-- Bootstrap core CSS -->
  <link href="../static/dist/css/bootstrap.min.css" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <!-- Custom styles for this template -->
  <link href="../static/dist/css/carousel.css" rel="stylesheet">
</head>

<body>

  <header>
    <!-- 수평메뉴 nav 클래스. 국민학교 ~ search 버튼까지-->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
      <img src="static/brand/school.png" width="2%" height="2%"> 
        <a class="navbar-brand" href="#"> P-Edu</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/home">Home</a>
            </li>

            {% if current_user.user_id != null %}
            <li class="nav-link active">
              {{current_user.user_id}}님 반갑습니다.
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/logout">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" href="/login_register">로그인/회원가입</a>
            </li>
            {% endif %}
          </ul>
          <!-- Search -->
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="검색" aria-label="검색">
            <!-- form-control 입력창 꾸며주는 클래스 -->
            <button class="btn btn-outline-success" type="submit">search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>

  <main>
    <!-- 슬라이드 버튼 검정색 처리 클래스명 변경-->
    <div id="myCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"
          aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="static/brand/jitsi.png" alt="" width="100%"
            height="100%" style="object-fit: contain;">

          <!--
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
        -->
          <div class="container">
            <div class="carousel-caption text-start">
             <h1 style="color:black;"><B>교육의 빈자리</B></h1>
              <p style="color:black;">화상연결으로 채워드립니다</p>
              <p><a class="btn btn-lg btn-danger" href="/bullet"  style="color:yellow;">시작하기</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img src="static/brand/두번째.png" alt="" width="100%" height="100%"
            style="object-fit: contain;">
          <!--
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
        -->
          <div class="container">
            <div class="carousel-caption text-start">
              <h1 style="color:black;"><B>비대면 스터디 그룹</B></h1>
              <p style="color:black;">함께 학습하며 궁금증을 해결해보세요.</p>
              <p><a class="btn btn-lg btn-primary" href="#">등록</a></p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <img src="static/brand/number3.png" alt="" width="100%" height="100%"
            style="object-fit: contain;">
          <!--
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
        -->
          <div class="container">
            <div class="carousel-caption text-end">
              <h1 style="color:black;"><B>p-edu에서</B></h1>
              <p style="color:black;">여러 기능들을 사용해보세요.</p>
              <p><a class="btn btn-lg btn-secondary" href="/bullet">지금 사용해보기</a></p>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>


    <!-- Marketing messaging and featurettes
  ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img src="static/brand/사용법.png" style="border-radius: 0%;" alt="" width="160" height="160"
            style="object-fit: contain;">
          <!--
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        -->

          <h2>How to use?</h2>
          <p>P-Edu는 어떻게 사용하나요?</p>
          <p><a class="btn btn-secondary" href="/tech_description">자세히 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img src="static/brand/스터디룸.png" style="border-radius: 0%;" alt="" width="160" height="160">
          <!--
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        -->
          <h2>Enter Study Room</h2>
          <p>화상으로 이어지는 스터디룸과 정보공유</p>
          <p><a class="btn btn-secondary" href="/bullet">자세히 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img src="static/brand/마이페이지.png" style="border-radius: 0%;" alt="" width="160" height="160">
          <!--
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        -->
          <h2>My Page</h2>
          <p>나의 정보 관리 및 수정</p>
          <p><a class="btn btn-secondary" href="/mypage/">자세히 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->


      

      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7">
          <!-- class="featurette-heading" -->
          <h2 class="h1">현재 진행중인 스터디룸
            <!--<span class="text-muted">Checkmate.</span>-->
          </h2>
          <p class="lead">함께 열공해요.<br> 건의사항 환영합니다.</p>
        </div>
        <p><a class="btn btn-secondary" href="/bullet">더보기</a></p>
        <div>
          <table class="table table-striped table-hover">
            <thead>
            </thead>
            <tbody>
              {% if rows!= none %}
              {% for row in rows %}
              <tr>
                <td>{{loop.index}}</td>
                <td>
                  <a href="{{ url_for('senior_school.article_page',title= row[2], context = row[3]) }}">
                    {{row[2]}}
                  </a>
                </td>
                <td>{{row[1]}}</td>
                <td>{{row[4]}}</td>
                <td>{{row[4]}}</td>
              </tr>
              {% endfor %}
              {% else %}
              <h3>데이터가 존재하지 않습니다.</h3>
              {% endif %}
            </tbody>
          </table>
        </div>
        
        </div> 
      </div>
      
    </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->


    <!-- FOOTER -->
    <footer class="container">
      <p class="float-end"><a href="#">Back to top</a></p>
      <p>&copy; 2021 Software Design Team 5. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
  </main>


  <script src="../static/dist/js/bootstrap.bundle.min.js"></script>


</body>

</html>

templates/login_register.html
<html>
    <head>
        <title>로그인 / 회원가입 폼 템플릿</title>
        <link rel="stylesheet" href="../static/dist/css/style.css">
    </head>
    <body>
        <div class="wrap">
            <div class="form-wrap">
                <div class="button-wrap">
                    <div id="btn"></div>
                    <button type="button" class="togglebtn" onclick="login()">LOG IN</button>
                    <button type="button" class="togglebtn" onclick="register()">REGISTER</button>
                </div>
                <div class="social-icons">
                    <img src="../static/brand/fb.png" alt="facebook">
                    <img src="../static/brand/tw.png" alt="twitter">
                    <img src="../static/brand/gl.png" alt="google">
                </div>
                <form id="login" method="POST" action="/set_login" class="input-group">
                    <input type="text" class="input-field" name="user_id" placeholder="User name or Email" required>
                    <input type="password" class="input-field" name="password" placeholder="Enter Password" required>
                    <input type="checkbox" class="checkbox"><span>Remember Password</span>
                    <button class="submit">Login</button>
                </form>
                <form id="register" method="POST" action="/set_register" class="input-group">
                    <input type="ID" class="input-field" id="user_id" placeholder="ID를 입력하세요"  name="user_id" required>
                    <input type="text" class="input-field" id="user_name" placeholder="이름을 입력해주세요" name="user_name" required>
                    <input type="password" class="input-field" id="password" placeholder="비밀번호를 입력해주세요" name="password" required>
                    <input type="checkbox" class="checkbox"><span>Terms and conditions</span>
                    <button class="submit">REGISTER</button>
                </form>
            </div>
        </div>
        <script>
            var x = document.getElementById("login");
            var y = document.getElementById("register");
            var z = document.getElementById("btn");
            
            
            function login(){
                x.style.left = "50px";
                y.style.left = "450px";
                z.style.left = "0";
            }

            function register(){
                x.style.left = "-400px";
                y.style.left = "50px";
                z.style.left = "110px";
            }
        </script>
    </body>
</html>

templates/mypage1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>My Page</h1>
    <h2><a class="nav-link active" aria-current="page" href="/home">Home</a></h2>

    {% if current_user.user_id != null %}
    <h3 class="nav-link active">
        {{current_user.user_id}}님 반갑습니다.
    </h3>
    <h3 class="nav-item">
        <a class="nav-link active" href="/logout">Logout</a>
    </h3>
    {% else %}
    <h3 class="nav-item">
        <a class="nav-link active" href="/login_register">로그인/회원가입</a>
    </h3>
    {% endif %}



    
</body>

</html>

templates/write_article.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h3>게시판</h3>
    <hr>
    <form action="/posting" method="POST" >
        제목<br>
        <input type="text" name="title" placeholder="제목을 입력해주세요"/><br>
        <hr>
        내용<br>
        <input type="text" name="context" style="text-align:center; width:400px; height:100px;" placeholder="내용을 입력해주세요" /><br><br>
        
        <input type="submit" value="업로드" /><br>
    </form>
</body>

</html>